spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: admin
        url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&characterEncoding=UTF-8
        username: test_user
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    security:
        oauth2:
            client:
                registration:
                    github:
                        clientId:
                        clientSecret:
                        redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
                        scope:
                            - user:email
                            - read:user
                provider:
                    github:
                        authorization-uri: https://github.com/login/oauth/authorize
                        token-uri: https://github.com/login/oauth/access_token
                        user-info-uri: https://api.github.com/user